# Generated by Django 5.1 on 2024-08-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perritossh3',
            name='Razaa',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='Razag',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='Razar',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='apeidodueno',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='correodueno',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='correovet',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='direcciondueno',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='direccionvet',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='nombrevet',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='numerovet',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='schedule_close',
        ),
        migrations.RemoveField(
            model_name='perritossh3',
            name='schedule_open',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='apeidodueno',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='correodueno',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='correovet',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='direcciondueno',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='direccionvet',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='nombrevet',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='numerovet',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='schedule_close',
        ),
        migrations.RemoveField(
            model_name='perritosssh2',
            name='schedule_open',
        ),
    ]
